In [1]:
import numpy as np
#import turtle
#import ch08.calcplotlib as plt

import calcplotlib as plt

In [2]:
# not working?
#%gui tk
plt.clear()
V = np.array([[ 0, -50, 0, 50],
[50, 0, -50, 0],
[ 1, 1, 1, 1],
[ 1, 1, 1, 1]])
plt.draw_quad(V)

In [3]:
plt.clear()
plt.draw_axes()


In [4]:
plt.clear()

plt.draw_axes()
V = np.array([[ 0, -50, 0, 50],
[50, 0, -50, 0],
[ 1, 1, 1, 1],
[ 1, 1, 1, 1]])
plt.draw_quad(V)

In [5]:
# Create 1D arrays
x = np.linspace(0, 2, 3)
y = np.linspace(2, 0, 3) # backwards!
print("x-coordinates:")
print(x)
print("y-coordinates:")
print(y)
# Create 2D arrays
X, Y = np.meshgrid(x, y)
print("x-coordinate grid:")
print(X)
print("y-coordinate grid:")
print(Y)

x-coordinates:
[0. 1. 2.]
y-coordinates:
[2. 1. 0.]
x-coordinate grid:
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
y-coordinate grid:
[[2. 2. 2.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [6]:
print(X+Y)

[[2. 3. 4.]
 [1. 2. 3.]
 [0. 1. 2.]]


In [7]:
def f(x, y):
    return 0.004 * (x ** 2 + y ** 2)
Z = f(X, Y)
print(Z)  

[[0.016 0.02  0.032]
 [0.004 0.008 0.02 ]
 [0.    0.004 0.016]]


In [8]:
Z_n = plt.normalize(Z)
print(Z_n)

[[0.5   0.625 1.   ]
 [0.125 0.25  0.625]
 [0.    0.125 0.5  ]]


In [3]:
def f(x, y):
    return 0.004 * (x ** 2 + y ** 2)

    
# Create the coordinate grids.
N = 20
x = np.linspace(-200, 200, N)
y = np.linspace(200, -200, N)
X, Y = np.meshgrid(x, y)
plt.clear()

# Compute the z-coordinates.
Z = f(X, Y)
# Plot the surface.
plt.plot_surface(X, Y, Z)

In [5]:
plt.clear()
# Compute the z-coordinates.
Z = f(X, Y)
# Compute the transformation matrix.
S = plt.scale3D(0.7, 0.7, 0.7)
R = plt.rotate_y(np.pi / 6) @ plt.rotate_x(np.pi / 3)
T = plt.translate3D(0, 0, -250)
A = S @ R @ T
# Plot the surface.
plt.plot_surface(X, Y, Z, A)