In [1]:
import numpy as np
#import turtle
#import ch08.calcplotlib as plt

import calcplotlib as plt

In [2]:
# not working?
#%gui tk
plt.clear()
V = np.array([[ 0, -50, 0, 50],
[50, 0, -50, 0],
[ 1, 1, 1, 1],
[ 1, 1, 1, 1]])
plt.draw_quad(V)

In [3]:
plt.clear()
plt.draw_axes()


In [4]:
plt.clear()

plt.draw_axes()
V = np.array([[ 0, -50, 0, 50],
[50, 0, -50, 0],
[ 1, 1, 1, 1],
[ 1, 1, 1, 1]])
plt.draw_quad(V)

In [5]:
# Create 1D arrays
x = np.linspace(0, 2, 3)
y = np.linspace(2, 0, 3) # backwards!
print("x-coordinates:")
print(x)
print("y-coordinates:")
print(y)
# Create 2D arrays
X, Y = np.meshgrid(x, y)
print("x-coordinate grid:")
print(X)
print("y-coordinate grid:")
print(Y)

x-coordinates:
[0. 1. 2.]
y-coordinates:
[2. 1. 0.]
x-coordinate grid:
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
y-coordinate grid:
[[2. 2. 2.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [6]:
print(X+Y)

[[2. 3. 4.]
 [1. 2. 3.]
 [0. 1. 2.]]


In [7]:
def f(x, y):
    return 0.004 * (x ** 2 + y ** 2)
Z = f(X, Y)
print(Z)  

[[0.016 0.02  0.032]
 [0.004 0.008 0.02 ]
 [0.    0.004 0.016]]


In [8]:
Z_n = plt.normalize(Z)
print(Z_n)

[[0.5   0.625 1.   ]
 [0.125 0.25  0.625]
 [0.    0.125 0.5  ]]


In [3]:
def f(x, y):
    return 0.004 * (x ** 2 + y ** 2)

    
# Create the coordinate grids.
N = 20
x = np.linspace(-200, 200, N)
y = np.linspace(200, -200, N)
X, Y = np.meshgrid(x, y)
plt.clear()

# Compute the z-coordinates.
Z = f(X, Y)
# Plot the surface.
plt.plot_surface(X, Y, Z)

In [5]:
plt.clear()
# Compute the z-coordinates.
Z = f(X, Y)
# Compute the transformation matrix.
S = plt.scale3D(0.7, 0.7, 0.7)
R = plt.rotate_y(np.pi / 6) @ plt.rotate_x(np.pi / 3)
T = plt.translate3D(0, 0, -250)
A = S @ R @ T
# Plot the surface.
plt.plot_surface(X, Y, Z, A)

In [4]:
from turtle import Turtle

def f(x, y):
    return 0.004 * (x ** 2 + y ** 2)


    
# Plot f(x, y) = 0.004(x^2 + y^2) in the standard basis.
plt.clear()
x = np.linspace(-200, 200, 20)
y = np.linspace(200, -200, 20)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)
plt.plot_surface(X, Y, Z)

# Define the gradient of f(x, y) = 0.004(x^2 + y^2).
def grad_f(x, y):
    df_dx = 0.008 * x
    df_dy = 0.008 * y
    return df_dx, df_dy

# Create a Turtle.
t = Turtle()
t.hideturtle()
t.speed(0)
t.penup()

t.color("gray100")
t.penup()

# Set the Turtle's initial position randomly and mark it.
x = 400 * (np.random.random() - 0.5)
y = 400 * (np.random.random() - 0.5)
t.goto(x, y)
t.pendown()

# Set the step size.
step_size = 1
# Descend the gradient for 500 steps.
num_steps = 500
for i in range(num_steps):
    x, y = t.pos()
    df_dx, df_dy = grad_f(x, y)
    x -= step_size * df_dx
    y -= step_size * df_dy
    t.goto(x, y)


In [6]:
poverty_pct = np.load("ch08/sdg_data/poverty_pct.npy")
food_insecure_pct = np.load("ch08/sdg_data/food_insecure_pct.npy")
child_mortality = np.load("ch08/sdg_data/child_mortality_per_100.npy")
maternal_mortality = np.load("ch08/sdg_data/maternal_mortality_per_100k.npy")
countries = np.load("ch08/sdg_data/countries.npy", allow_pickle=True)

In [7]:
print(f"===== SDG Indicator Data for {len(countries)} Countries =====")
print(f"Poverty: {poverty_pct[:5]}")
print(f"Food Insecurity: {food_insecure_pct[:5]}")
print(f"Child Mortality: {child_mortality[:5]}")
print(f"Maternal Mortality: {maternal_mortality[:5]}")
print(f"Countries: {countries[:5]}")

===== SDG Indicator Data for 104 Countries =====
Poverty: [2.1277364e-02 3.1122005e+01 7.8107830e-01 4.9709398e-01 4.8582220e-01]
Food Insecurity: [32.2 79.2  7.8 12.9  4.9]
Child Mortality: [0.9370933  6.401257   1.0044454  0.3665513  0.31263998]
Maternal Mortality: [  6.86681 183.20193  19.48496   2.333     6.10436]
Countries: ['Albania' 'Angola' 'Armenia' 'Australia' 'Austria']


In [9]:
import calclearn as ml

x = poverty_pct
y = child_mortality
w, b = ml.train(x, y)
print(f"w: {w:.03f} b: {b:.03f}")

w: 0.131 b: 0.769


In [11]:
# Set the input and output variables.
x = poverty_pct
y = child_mortality
# Train the regression model.
w, b = ml.train(x, y)
# Compute R^2.
y_hat = w * x + b
R2 = ml.r_squared(y, y_hat)
print("Child Mortality vs Poverty Percentage")
print(f"R2: {R2:.03f}")
print(f"w: {w:.03f} b: {b:.03f}")

Child Mortality vs Poverty Percentage
R2: 0.450
w: 0.138 b: 0.499
