In [1]:
import numpy as np

In [2]:
np.array([8, 6, 7, 5, 3, 0, 9])

array([8, 6, 7, 5, 3, 0, 9])

In [3]:
x = np.array([8, 6, 7, 5, 3, 0, 9])
x


array([8, 6, 7, 5, 3, 0, 9])

In [4]:
x[0]

np.int64(8)

In [5]:
x[0] = 2
x

array([2, 6, 7, 5, 3, 0, 9])

In [6]:
x[:3] = 1
x

array([1, 1, 1, 5, 3, 0, 9])

In [7]:
x = np.array([8.0, 6, 7, 5, 3, 0, 9])
x

array([8., 6., 7., 5., 3., 0., 9.])

In [8]:
x = np.array([8, 6, 7, 5, 3, 0, 9], dtype=np.float64)
x

array([8., 6., 7., 5., 3., 0., 9.])

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x = np.arange(0, 20, 5)
x

array([ 0,  5, 10, 15])

In [11]:
x = np.linspace(0, 1, 5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [13]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [16]:
x = np.random.random(5)
x

array([0.81124717, 0.93442047, 0.55106437, 0.15720764, 0.60173623])

In [17]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [18]:
2*x

array([0, 2, 4, 6, 8])

In [19]:
print(x/2, x**2, x%2)

[0.  0.5 1.  1.5 2. ] [ 0  1  4  9 16] [0 1 0 1 0]


In [20]:
a = np.array([1, 2])
b = np.array([3, 4])
a + b

array([4, 6])

In [21]:
5 * a + 6 * b

array([23, 34])

In [22]:
a*b

array([3, 8])

In [23]:
a@b

np.int64(11)

In [24]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
np.cross(a, b)

array([0, 0, 1])

In [25]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [26]:
print(np.sum(x))
print(np.max(x))
print(np.min(x))
print(np.clip(x, 0, 2))
print(np.sin(x))
print(np.cos(x))

10
4
0
[0 1 2 2 2]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [27]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.random.random((2, 2))

array([[0.81420894, 0.35163991],
       [0.45113578, 0.26620635]])

In [29]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [30]:
A = np.array([[1, 3],
[2, 4]])
A

array([[1, 3],
       [2, 4]])

In [31]:
A.shape

(2, 2)

In [32]:
print(A[0, 1]) # Element
print(A[:, 0]) # Column
print(A[-1, :]) # Row
print(A.T) # Transpose

3
[1 2]
[2 4]
[[1 2]
 [3 4]]


In [33]:
print(2*A, A/2, A**2, A%2)

[[2 6]
 [4 8]] [[0.5 1.5]
 [1.  2. ]] [[ 1  9]
 [ 4 16]] [[1 1]
 [0 0]]


In [34]:
np.sin(A)

array([[ 0.84147098,  0.14112001],
       [ 0.90929743, -0.7568025 ]])

In [36]:
np.cos(A)

array([[ 0.54030231, -0.9899925 ],
       [-0.41614684, -0.65364362]])

In [37]:
x = np.array([5, 6])
B = np.array([[5, 7],
[6, 8]])

In [43]:
print(A+B, A*B, A@B, A@x, sep="\n")

[[ 6 10]
 [ 8 12]]
[[ 5 21]
 [12 32]]
[[23 31]
 [34 46]]
[23 34]


In [42]:
A@x

array([23, 34])

In [44]:
A = np.array([[1, 3],
[2, 4]])
B = np.array([[1, 4],
[2, 5],
[3, 6]])
A + B

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [45]:
A@B 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [50]:
import numpy as np
import calcplotlib as plt
import turtle

In [51]:
# Set up the plot.
plt.clear()
#plt.draw_grid()
plt.draw_axes()
# Draw the reference point.
x = np.array([50, 100])
turtle.penup()
turtle.goto(x)
turtle.pensize(7)
turtle.color("gray80")
turtle.dot()
# Draw the transformed point.
S = np.array([[1, 0],
[0, 0.5]])

b = S @ x
turtle.penup()
turtle.goto(b)
turtle.pensize(7)
turtle.color("gray30")
turtle.dot()

In [53]:
# Set up the plot.
plt.clear()
#plt.draw_grid()
plt.draw_axes()
# Draw the reference point.
x = np.array([50, 100])
turtle.penup()

turtle.goto(x)
turtle.color("gray80")
turtle.pensize(7)
turtle.dot()
# Draw the rotated point.
angle = np.pi / 2
c = np.cos(angle)
s = np.sin(angle)
R = np.array([[c, -s],
[s, c]])
b = R @ x
turtle.penup()
turtle.goto(b)
turtle.color("gray30")
turtle.pensize(7)
turtle.dot()

In [55]:
# homogeneous coords

# Set up the plot
plt.clear()
#plt.draw_grid()
plt.draw_axes()
# Draw the reference point
x = np.array([50, 100, 1])
turtle.penup()
turtle.goto(x[:2])
turtle.color("gray80")
turtle.pensize(7)
turtle.dot()
# Draw the scaled point
S = np.array([[1, 0, 0],
[0, 0.5, 0],
[0, 0, 1]])
b = S @ x
turtle.penup()
turtle.goto(b[:2])
turtle.color("gray30")
turtle.pensize(7)
turtle.dot()
# Draw the rotated point
angle = np.pi / 2
c = np.cos(angle)
s = np.sin(angle)
R = np.array([[c, -s, 0],
[s, c, 0],
[0, 0, 1]])
b = R @ x
turtle.penup()

turtle.goto(b[:2])
turtle.color("gray50")
turtle.pensize(7)
turtle.dot()

In [57]:
# translation

# Set up the plot.
plt.clear()
#plt.draw_grid()
plt.draw_axes()
# Draw the reference point.
x = np.array([50, 100, 1])
turtle.penup()
turtle.goto(x[:2])
turtle.color("gray80")

turtle.pensize(7)
turtle.dot()
# Draw the translated point.
T = np.array([[1, 0, -200],
[0, 1, 75],
[0, 0, 1]])
b = T @ x
turtle.penup()
turtle.goto(b[:2])
turtle.color("gray30")
turtle.pensize(7)
turtle.dot()

In [59]:
# composition

# Set up the plot
plt.clear()
#plt.draw_grid()
plt.draw_axes()
# Draw the reference point.

x = np.array([50, 100, 1])
turtle.penup()
turtle.goto(x[:2])
turtle.color("gray80")
turtle.pensize(7)
turtle.dot()
# Translation matrix
T = np.array([[1, 0, -200],
[0, 1, 75],
[0, 0, 1]])
# Scale matrix
S = np.array([[1, 0, 0],
[0, 0.5, 0],
[0, 0, 1]])
# Rotation matrix
angle = np.pi / 2
c = np.cos(angle)
s = np.sin(angle)
R = np.array([[c, -s, 0],
[s, c, 0],
[0, 0, 1]])

# Translate, rotate, scale
b = S @ R @ T @ x
turtle.penup()
turtle.goto(b[:2])
turtle.color("gray30")
turtle.pensize(7)
turtle.dot()
# Rotate, translate, scale
b = S @ T @ R @ x
turtle.penup()
turtle.goto(b[:2])
turtle.color("gray50")
turtle.pensize(7)
turtle.dot()

In [61]:
# meshes

# Set up the plot.
plt.clear()
#plt.draw_grid()
plt.draw_axes()
# Set the vertices.
V = np.array([[1, -1, -1, 1],
[1, 1, -1, -1],
[1, 1, 1, 1]])
# Scale matrix
S = np.array([[100, 0, 0],
[ 0, 100, 0,],[ 0, 0, 1]])

# Transform the vertices.
V = S @ V
# Draw the vertices.
turtle.penup()
turtle.color("gray30")
turtle.pensize(7)
rows, cols = V.shape
for j in range(cols):
    turtle.goto(V[0:2, j])
    turtle.dot()

              

In [62]:
# Set the edges
A = np.array([[0, 1, 0, 1],
[1, 0, 1, 0],
[0, 1, 0, 1],
[1, 0, 1, 0]])
# Draw the edges
turtle.penup()
turtle.color("gray30")
turtle.pensize(2)
for j in range(cols):
    for i in range(j, cols):
        if A[i, j] == 1:
            turtle.goto(V[0:2, j])
            turtle.pendown()
            turtle.goto(V[0:2, i])
            turtle.penup()
        
