In [1]:
import numpy as np

In [2]:
np.array([8, 6, 7, 5, 3, 0, 9])

array([8, 6, 7, 5, 3, 0, 9])

In [3]:
x = np.array([8, 6, 7, 5, 3, 0, 9])
x


array([8, 6, 7, 5, 3, 0, 9])

In [4]:
x[0]

np.int64(8)

In [5]:
x[0] = 2
x

array([2, 6, 7, 5, 3, 0, 9])

In [6]:
x[:3] = 1
x

array([1, 1, 1, 5, 3, 0, 9])

In [7]:
x = np.array([8.0, 6, 7, 5, 3, 0, 9])
x

array([8., 6., 7., 5., 3., 0., 9.])

In [8]:
x = np.array([8, 6, 7, 5, 3, 0, 9], dtype=np.float64)
x

array([8., 6., 7., 5., 3., 0., 9.])

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x = np.arange(0, 20, 5)
x

array([ 0,  5, 10, 15])

In [11]:
x = np.linspace(0, 1, 5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [13]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [16]:
x = np.random.random(5)
x

array([0.81124717, 0.93442047, 0.55106437, 0.15720764, 0.60173623])

In [17]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [18]:
2*x

array([0, 2, 4, 6, 8])

In [19]:
print(x/2, x**2, x%2)

[0.  0.5 1.  1.5 2. ] [ 0  1  4  9 16] [0 1 0 1 0]


In [20]:
a = np.array([1, 2])
b = np.array([3, 4])
a + b

array([4, 6])

In [21]:
5 * a + 6 * b

array([23, 34])

In [22]:
a*b

array([3, 8])

In [23]:
a@b

np.int64(11)

In [24]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
np.cross(a, b)

array([0, 0, 1])

In [25]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [26]:
print(np.sum(x))
print(np.max(x))
print(np.min(x))
print(np.clip(x, 0, 2))
print(np.sin(x))
print(np.cos(x))

10
4
0
[0 1 2 2 2]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
